import { statSync } from "node:fs";
import path from "node:path";
import type { CloakMap } from "./types.js";

const DEFAULT_MAP_FILE = "prismacloak.map.json";

export function defaultMapPath(schemaPath: string): string {
  const resolved = path.resolve(schemaPath);
  const dir = statSync(resolved).isDirectory()
    ? path.dirname(resolved)
    : path.dirname(resolved);

  return path.join(dir, DEFAULT_MAP_FILE);
}

export function defaultShadowPath(schemaPath: string): string {
  const resolved = path.resolve(schemaPath);

  if (statSync(resolved).isDirectory()) {
    return `${resolved}.shadow.prisma`;
  }

  return resolved.replace(/\.prisma$/i, ".shadow.prisma");
}

export function redactSchema(schemaText: string, map: CloakMap): string {
  let output = schemaText;

  output = redactDatasourceUrl(output);
  output = replaceEnumBlocks(output, map);
  output = replaceModelBlocks(output, map);

  return `${output.trim()}\n\n// Generated by PrismaCloak — safe for LLM context. Do not use in production.\n`;
}

function redactDatasourceUrl(schemaText: string): string {
  return schemaText.replace(
    /(url\s*=\s*")([^"]+)(")/g,
    '$1postgresql://REDACTED:REDACTED@localhost:5432/REDACTED$3',
  );
}

function replaceEnumBlocks(schemaText: string, map: CloakMap): string {
  return schemaText.replace(
    /enum\s+(\w+)\s*\{([^}]*)\}/gs,
    (_fullMatch, enumName: string, body: string) => {
      const shadowEnum = map.enums[enumName];
      if (!shadowEnum) {
        return _fullMatch;
      }

      let newBody = body;
      const valueMap = map.enumValues[enumName] ?? {};
      const replacements = Object.entries(valueMap).sort(
        (a, b) => b[0].length - a[0].length,
      );

      for (const [original, shadow] of replacements) {
        newBody = replaceIdentifier(newBody, original, shadow);
      }

      return `enum ${shadowEnum} {${newBody}}`;
    },
  );
}

function replaceModelBlocks(schemaText: string, map: CloakMap): string {
  return schemaText.replace(
    /model\s+(\w+)\s*\{([^}]*)\}/gs,
    (_fullMatch, modelName: string, body: string) => {
      const shadowModel = map.models[modelName];
      if (!shadowModel) {
        return _fullMatch;
      }

      let newBody = body;

      newBody = replaceQuotedMaps(newBody, modelName, map);
      newBody = replaceFields(newBody, modelName, map);
      newBody = replaceEnumValueReferences(newBody, map);
      newBody = replaceTypeReferences(newBody, map);

      return `model ${shadowModel} {${newBody}}`;
    },
  );
}

function replaceQuotedMaps(body: string, modelName: string, map: CloakMap): string {
  let output = body;

  for (const [original, shadow] of Object.entries(map.tableMaps)) {
    output = output.replace(
      new RegExp(`(@@map\\(\\s*")${escapeRegExp(original)}("\\s*\\))`, "g"),
      `$1${shadow}$2`,
    );
  }

  const columnMap = map.columnMaps[modelName] ?? {};
  for (const [original, shadow] of Object.entries(columnMap)) {
    output = output.replace(
      new RegExp(`(@map\\(\\s*")${escapeRegExp(original)}("\\s*\\))`, "g"),
      `$1${shadow}$2`,
    );
  }

  return output;
}

function replaceFields(body: string, modelName: string, map: CloakMap): string {
  const fieldMap = map.fields[modelName] ?? {};
  const replacements = Object.entries(fieldMap).sort(
    (a, b) => b[0].length - a[0].length,
  );

  let output = body;
  for (const [original, shadow] of replacements) {
    output = replaceIdentifier(output, original, shadow);
  }

  return output;
}

function replaceEnumValueReferences(body: string, map: CloakMap): string {
  const valueReplacements: Array<[string, string]> = [];

  for (const valueMap of Object.values(map.enumValues)) {
    for (const [original, shadow] of Object.entries(valueMap)) {
      valueReplacements.push([original, shadow]);
    }
  }

  valueReplacements.sort((a, b) => b[0].length - a[0].length);

  let output = body;
  for (const [original, shadow] of valueReplacements) {
    output = replaceIdentifier(output, original, shadow);
  }

  return output;
}

function replaceTypeReferences(body: string, map: CloakMap): string {
  const typeReplacements: Array<[string, string]> = [
    ...Object.entries(map.models),
    ...Object.entries(map.enums),
  ].sort((a, b) => b[0].length - a[0].length);

  let output = body;
  for (const [original, shadow] of typeReplacements) {
    output = replaceIdentifier(output, original, shadow);
  }

  return output;
}

function replaceIdentifier(text: string, original: string, shadow: string): string {
  const pattern = new RegExp(`(?<![\\w@])${escapeRegExp(original)}(?![\\w])`, "g");
  return text.replace(pattern, shadow);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export { DEFAULT_MAP_FILE };
